---
title: "Jazz recordings"
author: "VP"
date: "6 1 2022"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(RColorBrewer)

knitr::opts_chunk$set(echo = TRUE)

my_theme <- theme(
  panel.grid       = element_blank(),
  panel.background = element_rect(fill  = "white", colour = NA),
  axis.title.x     = element_text(
                       size = 12, 
                       vjust = -1
                     ),
  axis.title.y     = element_text(size = 12)
)
```

```{r data import and data preparation, include=FALSE}
data <- read.csv("data/ECM_releases.csv", encoding = "UTF-8")

data$release_year <- as.integer(stringr::str_remove(data$release_year, "\\?"))

data <- data %>% 
  tidyr::drop_na(musician_name)
```


```{r search instruments, include=FALSE}
# https://stackoverflow.com/questions/57000390/how-to-recode-multiple-values-in-vector-into-one-value
unique(data$musician_instruments[
  stringr::str_detect(data$musician_instruments, "[A-Z]") & 
  !is.na(data$musician_instruments)
])

unique(data$musician_instruments[
  stringr::str_detect(data$musician_instruments, "guitar") & 
  !is.na(data$musician_instruments)
])

data[stringr::str_detect(data$musician_instruments, "flute") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE)

data[stringr::str_detect(data$musician_instruments, "horn") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE)

data[stringr::str_detect(as.character(data$musician_instruments), "bass") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE)

data[stringr::str_detect(as.character(data$musician_instruments), "harp") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE)

data[stringr::str_detect(as.character(data$musician_instruments), "ion") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE)

data[stringr::str_detect(as.character(data$musician_instruments), "piano") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  pull(musician_instruments)

drum <- data[stringr::str_detect(as.character(data$musician_instruments), "drum") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  pull(musician_instruments)

flute <- data[stringr::str_detect(as.character(data$musician_instruments), "flute") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  pull(musician_instruments)

data[stringr::str_detect(data$musician_instruments, "violin") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE)

unique(data$musician_instruments)
```


```{r recode instruments, warning=FALSE}
data <- data %>% 
  mutate(
    musician_instruments = forcats::fct_recode(
      musician_instruments,
      oboe        = "English horn",
      viola       = "alto violin"
    ),
    musician_instruments = forcats::fct_collapse(
      musician_instruments,
      synthesizer = c("guitar synthesizer", "ARP 2600 synthesizer"),
      trombone    = c("bass trombone", "contrabass trombone"),
      electronics = c(
        "live electronics", 
        "electronic effects", 
        "electronic treatments", 
        "electronic keyboards",
        "live and studio electronics",
        "electric"
      ),
      cello = c(
        "8-string electric cello", 
        "acoustic cello", 
        "8-string solid body electric cello"
      ), 
      Klavier = c(
        "piano",
        "prepared piano",
        "electric piano",
        "toy piano",
        "acoustic piano",
        "Bechstein piano",
        "Tac piano",
        "Wurlitzer piano",     
        "Fender Rhodes piano",
        "Fortepiano",
        "Hohner Electra piano",
        "Rhodes piano",
        "solo piano",
        "Steinway piano",
        "tangent piano" 
      ),
      Saxophon = c(
        "sax",
        "soprano sax",
        "alto sax",
        "tenor sax",
        "baritone sax",
        "bass sax",
        "taragato",
        "tarogato",
        "sopranino sax"
      ),
      clarinet = c(
        "1st basset horn",
        "2nd basset horn",
        "bass clarinet", 
        "contrabass clarinet",
        "alto clarinet",
        "piccolo clarinet",
        "B flat clarinet",
        "contra alto clarinet",
        "1st clarinet",
        "2nd clarinet",
        "A clarinet",
        "E flat clarinet",
        "Meraaker clarinet"
      ),
      contrabass = c(
        "double bass",
        "electric double bass",
        "string bass"
      ),
      Gesang = c(
        "vocals",
        "backing vocals",
        "voices",
        "voice"
      ),
      Gitarren = c(
        "guitar",
        "classical guitar",
        "electric guitar",
        "10-string guitar",
        "acoustic guitar",
        "12-string guitar",                          
        "electric 12-string guitar",
        "6-string guitar",
        "6-string electric guitar",
        "8-string guitar",
        "10-string guitar",
        "6 & 12-string guitar",
        "10 & 14-string guitar",
        "electric 6 & 12-string guitar",
        "super 8-string guitar",
        "electric and acoustic 6 & 12-string guitar",
        "electronic guitar",
        "Spanish classical guitar",
        "pedal steel guitar",
        "baritone guitar",
        "flamenco guitar",
        "slide guitar",
        "guitars",
        "mandolin guitar",
        "15-string harp guitar",
        "acoustic bass",
        "acoustic bass guitar",
        "electric mandolin",
        "mandolin",
        "Baroque guitar",
        "mandola",
        "lute",
        "lauto",
        "outi",
        "sitar",
        "banjo",
        "electric oud",
        "oud",
        "chitarrone",
        "Constantinople lyra",
        "lyra"
      ),
      "bass guitar" = c(
        "electric bass",
        "Fender bass",
        "6 & 4-string Fender bass",
        "6 & 4-string electric bass",
        "6 & 4-string bass",
        "F bass"
      ),
      "Flöten" = c(
        "flute",
        "bass recorder",
        "recorder",
        "great bass recorder",
        "sopranino",
        "piccolo",
        "nay",
        "shakuhachi",
        "tin whistle",
        "whistle",
        "whistles"
      ),
      "French horn" = c(
        "tenor horn",
        "flugelhorn",
        "baritone horn"
      ),
      "vibes, marimba, chimes, etc." = c(
        "vibes",
        "bowed vibes",
        "tenor vibes",
        "vibraharp",
        "marimba",
        "xylophone",
        "glockenspiel",
        "chimes",
        "melody chimes"
      ),
      violin = c(
        "Baroque violin",
        "double violin",
        "10-string double violin",
        "electric 6-string violin",
        "violino d'amore",
        "10-string stereophonic double violin",
        "1st violin",
        "2nd violin",			
        "6-string electric violin",
        "lead violin",
        "Hardanger fiddle",
        "fiddle",
        "drone fiddle",
        "electric violin"
      ),
      accordion = c(
        "bandoneon",
        "accordion bayan",
        "bayan",
        "low accordion"
      ),
      trumpet = c(
        "piccolo trumpet",
        "pocket trumpet",
        "lead trumpet"
      ),
      organ = c(
        "Hammond B-3 organ",
        "Hammond organ",
        "pipe organ",
        "trinity organ",
        "church organ",
        "electronic organ",
        "organ samples",
        "portable organ",
        "positive organ"
      ),
      harp = c(
        "Baroque harp",
        "wind harp",
        "folk harp",			
        "Celtic harp",			
        "triple harp",
        "Gothic harp",
        "Italian harp",
        "Italian triple harp",
        "Spanish harp"
      ),
      drums = c(
        drum, 
        "tabla", 
        "darbouka", 
        "congas", 
        "bongos",
        "djembe"
      ),
      mbira = c(
        "sanza",
        "kalimba"
      )
    )
  ) %>% 
  filter(!(musician_instruments %in% c( 
    "soprano", # exclude singing because instrument and voice labels are ambiguous
    "mezzo-soprano",
    "alto",    # (e.g. "tenor": "tenor voice" or "tenor sax"?)
    "contralto",
    "tenor",
    "baritone",
    "bass",
    "bassu voice",
    "composer",
    "conductor",
    "music",
    "countertenor",
    "text",
    "arranger",
    "samples",
    "poems",
    "words",
    "live samples",
    "lyrics",
    "Anita O'Day",
    "Vito D'Angelo",
    "director",
    "traditional",
    "artistic director",
    "Zeuge Schwab: Heinz E. Hirscher",
    "narrator",
    "choirmaster",
    "programs",
    "transcriber",
    "chorus director",
    "Stuttgart",
    "String Orchestra director",
    "sound processing",
    "vocal arranger",
    "wind and perciussion orchestra"
  )))

perc <- data[stringr::str_detect(data$musician_instruments, "perc") & 
  !is.na(data$musician_instruments),] %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  pull(musician_instruments) %>% 
  as.character()

data <- data %>% 
  mutate(
    musician_instruments = forcats::fct_collapse(
      musician_instruments,
      Schlaginstrumente = c(
        perc, 
        "percussion",
        "drums",
        "bells",
        "timpani",
        "cowbell",
        "African double cowbell",
        "bongos",
        "bendir",
        "maracas",
        "cymbals",
        "tuned tambourine",
        "tambourine",
        "small tambourine",
        "South American shakers",
        "shakers",
        "woodblock",
        "ching",
        "crotales",
        "ghatam",
        "gong",
        "gongs",
        "cabasa"
      )
    )
  )

data %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  slice_max(n, n = 30)
```

```{r collapse instrument groups}
data <- data %>% 
  mutate(
    musician_instruments = forcats::fct_collapse(
      musician_instruments,
        Saiteninstrumente = c(
        "strings",
        "baritone violin",			
        "bass violin",			
        "contrabass",
        "viola d'amore",
        "viola da gamba",
        "nyckelharpa",
        "string ensemble",
        "pianolin",
        "violone",
        "cello",
        "viola",
        "violin",
        "RAAD electro acoustic strings",
        "harp",
        "berimbau",
        "tambura", #
        "hammered dulcimer",
        "doussn'gouni",
        "kantele",
        "santouri",
        "Bavarian zither",
        "2 Bavarian zither",
        "autoharp",
        "kamancheh",
        "koto"
      ),
      Blechblasinstrumente = c(
        "brass",
        "trombone",
        "trumpet",
        "tuba",
        "French horn",
        "lead trombone",
        "alto trombone",
        "clarino",
        "bike horns",
        "cornet"
      ),
      "Andere Holzblasinstrumente" = c(
        "other woodwind",
        "woodwinds",
        "bassoon",
        "clarinet",
        "oboe",
        "oboe d'amore",
        "flute",
        "read",
        "reeds",
        "duduk",
        "shawm",
        "didgeridoo",
        "harmonica",
        "musette",
        "bagpipes",
        "border pipes",
        "pitch pipe",
        "Swedish bagpipes",
        "whirlpipe"
      ),
      "Elektronische Instrumente" = c("electronics", "synthesizer"),
      Gitarren = c("bass guitar", "guitar"),
      Tasteninstrumente = c(
        "keyboard instruments",
        "organ",
        "accordion",
        "keyboards",
        "celeste",
        "clavichord",
        "harmonium",
        "harpsichord",
        "melodica"
      )
    )
  )

data %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  slice_max(n, n = 30)
```


```{r most frequet instruments}
most_frequent_instruments <- data %>% 
  group_by(musician_instruments) %>% 
  count(sort = TRUE) %>% 
  filter(n >= 17) %>% 
  select(musician_instruments)

data <- data %>% 
  filter(musician_instruments %in% most_frequent_instruments$musician_instruments)

data$musician_instruments <- droplevels(data$musician_instruments)
```

```{r include only unique combinations}
data <- data %>% 
  mutate(counter = 1) %>% 
  group_by(release_num, release_name, release_year, musician_name) %>% 
  arrange(desc(musician_instruments)) %>% 
  mutate(cumsum = cumsum(counter)) %>% 
  filter(cumsum == 1) %>% 
  select(-c(counter, cumsum)) %>% 
  ungroup()
```

```{r decade}
release_year_range <- data %>% 
  summarise(
    min_release_year = min(release_year, na.rm = TRUE), 
    max_release_year = max(release_year, na.rm = TRUE)
  ) %>% 
  as.matrix()

data <- data %>% 
  mutate(release_decade = cut(
    x = release_year,
    breaks = seq(release_year_range[1] - 1, release_year_range[2] + 9, 10),
    labels = c("1970er", "1980er", "1990er", "2000er", "2010er"),
    ordered_result = TRUE
  ))

data %>% 
  group_by(release_year, release_decade) %>% 
  count()

# table(data$release_year, data$release_decade)

sum(is.na(data$release_decade))

data <- data %>% 
  tidyr::drop_na(release_decade)
  
group.colors.5 <- brewer.pal(9, "Oranges")[3:7]
names(group.colors.5) <- unique(data$release_decade)
```

```{r hist}
data %>% 
  ggplot( 
    aes(
      x     = release_year,
      # color = musician_instruments,
      fill  = musician_instruments
    )) +
  geom_histogram(alpha = .5, binwidth = 5) +
  my_theme

data %>% 
  ggplot( 
    aes(
      x     = release_decade,
      # color = musician_instruments,
      fill  = musician_instruments
    )) +
  geom_bar(alpha = .5, binwidth = 5) +
  my_theme
```

```{r fill hist}
data %>% 
  ggplot( 
    aes(
      x     = release_year,
      # color = musician_instruments,
      fill  = musician_instruments
    )) +
  geom_histogram(alpha = .5, position = "fill") +
  my_theme
```

```{r flipped plot}
table(data$musician_instruments, data$release_decade)

data %>%
  mutate(musician_instruments = musician_instruments %>% 
    forcats::fct_lump_n(7) %>% 
    forcats::fct_infreq()
  ) %>% 
  filter(musician_instruments != "Other") %>% 
  group_by(musician_instruments) %>% 
  mutate(n = n(), release_decade = release_decade) %>% 
  select(musician_instruments, n, release_decade) %>% 
  arrange(desc(n)) %>% 
  ungroup() %>% 
  ggplot( 
    aes(
      x     = forcats::fct_reorder(musician_instruments, n),
      fill  = release_decade
    )) +
  geom_bar(binwidth = 5) +
  labs(x = "Instrumente", y = "Anzahl", title = "Intrumente", fill = "Jahrzehnt") +
  scale_fill_manual(values = group.colors.5) +
  geom_text(aes(label = n, y = n + 40)) +
  coord_flip() +
  my_theme
```

```{r flipped plot 2}
group.colors.7 <- brewer.pal(7, "Oranges")

group.colors.8 <- c(brewer.pal(19, "Oranges")[1], group.colors.7)
# names(group.colors.7) <- table(data$musician_instruments)

plot_data2 <- data %>%
  mutate(musician_instruments = musician_instruments %>%
    forcats::fct_infreq() %>% 
    forcats::fct_lump_n(7) %>% 
    forcats::fct_rev()
  ) %>% 
  group_by(release_decade) %>% 
  mutate(n = n()) %>% 
  select(musician_instruments, n, release_decade) %>% 
  arrange(desc(n)) %>% 
  ungroup()

table(plot_data2$release_decade, plot_data2$musician_instruments)

plot_data2 %>% 
  ggplot( 
    aes(
      x    = release_decade,
      fill = musician_instruments
    )) +
  geom_bar(binwidth = 5) +
  labs(x = "", y = "", fill = "") +
  scale_fill_manual(values = group.colors.8) +
  geom_text(aes(label = n, y = n + 40)) +
  my_theme

plot_data2 %>% 
  ggplot( 
    aes(
      x    = release_decade,
      color = musician_instruments#,
      # group = musician_instruments
    )
  ) +
  geom_bar(binwidth = 5, fill = "white") +
  labs(x = "", y = "", color = "") +
  scale_fill_manual("white") +
  geom_text(aes(label = n, y = n + 40)) +
  my_theme
```

